news/urls.py
from django.urls import path
from news.views import blog_delete, blog_update, index, blog, blog_add, blog_details, about, contact, news_details, category

urlpatterns = [
    path('', index, name='index'),
    path('blog', blog, name='blog'),
    path('blog/add', blog_add, name='blog_add'),
    path('blog/<slug>', blog_details, name='blog_details'),
    path('blog/<slug>/update', blog_update, name='blog_update'),
    path('blog/<slug>/delete',blog_delete, name='blog_delete'),
    path('about', about, name='about'),
    path('contact', contact, name='contact'),
    path('news/<slug>', news_details, name='news_details'),
    path('category/<slug>', category, name='category'),
]

newsportal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('news.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header="News Portal"
admin.site.index_title="Admin Section"
admin.site.site_title="Admin Administration"

news/models.py
from re import T
from tabnanny import verbose
from tkinter import CASCADE
from turtle import title
from unicodedata import category
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify

# Create your models here.


class Setting(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=100, null=True, blank=True)
    logo = models.ImageField(upload_to="images/", null=True, blank=True)
    favicon = models.ImageField(upload_to="images/", null=True, blank=True)
    facebook = models.CharField(max_length=100, null=True, blank=True)
    twitter = models.CharField(max_length=100, null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True, blank=True)
    linkedin = models.CharField(max_length=100, null=True, blank=True)
    youtube = models.CharField(max_length=100, null=True, blank=True)
    google = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Settings'

    def __str__(self):
        return self.name


class Category(models.Model):
    category_name = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name


class News(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=100, null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    intro = RichTextField(null=True, blank=True)
    content = RichTextField(null=True, blank=True)
    views = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'News'

    def __str__(self):
        return self.title


class Blog(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=100, null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    intro = RichTextField(null=True, blank=True)
    content = RichTextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Blog'

    def __str__(self):
        return self.title

news/views.py
from django import views
from django.shortcuts import render, redirect
from .models import *
from django.contrib import messages
import os
from django.utils.text import slugify
from django.db.models import Q, Count
from django.core.mail import send_mail


# Create your views here.


def index(request):
    q = request.GET.get('search') if request.GET.get('search') != None else ''
    newsData = News.objects.filter(
        Q(title__icontains=q) |
        Q(author__icontains=q) |
        Q(intro__icontains=q)
    ).all()
    CategoryData = Category.objects.all()
    most_viewed_news = News.objects.annotate(Count('views')).order_by('-views__count')[:3]
    data = {
        'most_viewed_news': most_viewed_news,
        'newsData': newsData,
        'CategoryData': CategoryData,
    }
    return render(request, 'pages/home/index.html', data)


def about(request):
    data = {
        'title': "About Us"
    }
    return render(request, 'pages/about/about.html', data)


def contact(request):
    # if request.method == "POST":
    #     send_mail(
    #         'Subject here',
    #         'Here is the message.',
    #         'mandip698@gmail.com',
    #         ['mandip698@gmail.com'],
    #         fail_silently=False,
    #     )
    data = {
        'newsData': News.objects.all(),
        'title': "Contact Us",

    }
    return render(request, 'pages/contact/contact.html', data)


def news_details(request, slug):
    n_obj = News.objects.get(slug=slug)
    related_news = News.objects.filter(
        category=n_obj.category).exclude(slug=slug)
    n_obj.views += 1
    n_obj.save()
    most_viewed_news = News.objects.filter(
        category=n_obj.category).exclude(slug=slug).annotate(Count('views')).order_by('-views__count')[:1]
    data = {
        'newsData': News.objects.get(slug=slug),
        'CategoryData': Category.objects.all(),
        'related_news': related_news,
        'most_viewed_news': most_viewed_news,
    }
    return render(request, 'pages/news/news_details.html', data)


def category(request, slug):
    data = {
        'newsData': News.objects.filter(category__category_name=slug),
    }
    return render(request, 'pages/news/category.html', data)


def blog(request):
    data = {
        'blogsData': Blog.objects.all(),
        'title': "Blog",
    }
    return render(request, 'pages/blogs/blog.html', data)


def blog_details(request, slug):
    data = {
        'blogsData': Blog.objects.get(slug=slug),
        'title': "Blog",
    }
    return render(request, 'pages/blogs/blog_details.html', data)


def blog_add(request):
    if request.method == "POST":
        title = request.POST['title']
        author = request.POST['author']
        intro = request.POST['intro']
        content = request.POST['content']
        slug = slugify(request.POST['title'])
        image = ''
        if request.FILES:
            image = request.FILES['image']
            Blog.objects.create(
                title=title, author=author, intro=intro, content=content, slug=slug, image=image
            )
        messages.success(request, 'Blog Added Successfully')
        return redirect('blog')
    else:
        data = {
            'blogsData': Blog.objects.all(),
            'title': "Blog",
        }
        return render(request, 'pages/blogs/blog_add.html', data)


def delete_file(slug):
    f_data = Blog.objects.get(slug=slug)
    if f_data.image:
        file_path = os.getcwd() + f_data.image.url
        if os.path.exists(file_path):
            os.remove(file_path)
            return True
        else:
            return True
    else:
        return True

# delete file function


def blog_delete(request, slug):
    if delete_file(slug) and Blog.objects.get(slug=slug).delete():
        messages.success(request, 'Blog Deleted Successfully')
        return redirect('blog')
    else:
        return redirect('blog')


def blog_update(request, slug):
    if request.method == "POST":
        bObj = Blog.objects.get(slug=slug)
        bObj.title = request.POST['title']
        bObj.author = request.POST['author']
        bObj.intro = request.POST.get('intro')
        bObj.content = request.POST.get('content')
        bObj.slug = slugify(request.POST['title'])
        image = ''
        if request.FILES:
            delete_file(slug)
            image = request.FILES['image']
        bObj.image = image
        bObj.save()
        messages.success(request, 'Blog Updated Successfully')
        return redirect('blog')
    else:
        data = {
            'title': "Blog",
            'blogsData': Blog.objects.get(slug=slug)
        }
        return render(request, 'pages/blogs/blog_update.html', data)

news/templates/layouts/footer.html
{% load static %}     
        <!-- Footer Start -->
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Get in Touch</h3>
                            <div class="contact-info">
                                <p><i class="fa fa-map-marker"></i>{{settingData.address}}</p>
                                <p><i class="fa fa-envelope"></i>{{settingData.email}}</p>
                                <p><i class="fa fa-phone"></i>{{settingData.phone}}</p>
                                <div class="social">
                                    <a href=""><i class="fab fa-twitter"></i></a>
                                    <a href=""><i class="fab fa-facebook-f"></i></a>
                                    <a href=""><i class="fab fa-linkedin-in"></i></a>
                                    <a href=""><i class="fab fa-instagram"></i></a>
                                    <a href=""><i class="fab fa-youtube"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Quick Links</h3>
                            <ul>
                                <li>
                                    {% for category in menuCategory %}
                                    <a href="{% url 'category' category.category_name %}">{{category.category_name}}</a>
                                    {% endfor %}
                                </li>
                                <li><a href="{% url 'blog' %}">Blog</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- <div class="col-lg-3 col-md-6">
                        <div class="footer-widget">
                            <h3 class="title">Newsletter</h3>
                            <div class="newsletter">
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sed porta dui. Class aptent taciti sociosqu
                                </p>
                                <form>
                                    <input class="form-control" type="email" placeholder="Your email here">
                                    <button class="btn">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
        <!-- Footer End -->
        
        <!-- Footer Menu Start -->
        <div class="footer-menu">
            <div class="container">
                <div class="f-menu">
                    <a href="">Terms of use</a>
                    <a href="">Privacy policy</a>
                    <a href="">Cookies</a>
                    <a href="">Accessibility help</a>
                    <a href="">Advertise with us</a>
                    <a href="{% url 'contact' %}">Contact us</a>
                </div>
            </div>
        </div>
        <!-- Footer Menu End -->

        <!-- Footer Bottom Start -->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 copyright">
                        <p>Copyright &copy; <a href="">{{settingData.name}}</a>. All Rights Reserved</p>
                    </div>

                    <div class="col-md-6 template-by">
                        <p>Template By <a href="{% url 'index' %}">HTML Codex</a></p>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer Bottom End -->

        <!-- Back to Top -->
            <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/slick/slick.min.js' %}"></script>

        <!-- Template Javascript -->
        <script src="{% static 'js/main.js' %}"></script>

news/templates/layouts/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% if title %}
            <title>{{title}}</title>
        {% else %}
            <title>{{ 'Home' }}</title>
        {% endif %}
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Bootstrap News Template - Free HTML Templates" name="keywords">
        <meta content="Bootstrap News Template - Free HTML Templates" name="description">

        <!-- Favicon -->
        <link href="img/favicon.ico" rel="icon">

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet"> 

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="{% static 'lib/slick/slick.css' %}" rel="stylesheet">
        <link href="{% static 'lib/slick/slick-theme.css' %}" rel="stylesheet">
        {% if settingData.favicon %}
                    <link rel="icon" href="{{settingData.favicon.url}}">
    
                    {% endif %}

        <!-- Template Stylesheet -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <body>

news/templates/layouts/navbar.html
{% load static %}
<!-- Nav Bar Start -->
        <div class="nav-bar">
            <div class="container">
                <nav class="navbar navbar-expand-md bg-dark navbar-dark">
                    <a href="#" class="navbar-brand">MENU</a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto">
                            <a href="{% url 'index' %}" class="nav-item nav-link">Home</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Category</a>
                                <div class="dropdown-menu">
                                    {% for category in menuCategory %}
                                    <a href="{% url 'category' category.category_name %}" class="dropdown-item">{{category.category_name}}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            <a href="{% url 'blog' %}" class="nav-item nav-link">Blog</a>
                            <a href="{% url 'about' %}" class="nav-item nav-link">About</a>
                            <a href="{% url 'contact' %}" class="nav-item nav-link">Contact Us</a>
                        </div>
                        <div class="social ml-auto">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Nav Bar End -->

news/templates/layouts/top-header.html
{% load static %}
<!-- Brand Start -->
<div class="brand">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4">
                <div class="b-logo">
                    {% if settingData.logo %}
                    <a href="{% url 'index' %}">
                        <img src="{{settingData.logo.url}}" alt="Logo">
                    </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-6 col-md-4">
                <div class="b-ads">
                    <a href="https://htmlcodex.com" target="_blank">
                        <img src="/news/uploads/images/ads.jpg" alt="Ads">
                    </a>
                </div>
            </div>
            <div class="col-lg-3 col-md-4">
                <form action="{% url 'index' %}" method="get">
                <div class="b-search">
                    <input type="text" name="search" placeholder="Search">
                    <button><i class="fa fa-search"></i></button>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>
<!-- Brand End -->

news/templates/master/master.html
{% include 'layouts/header.html' %}
{% include 'layouts/top-header.html' %}
{% include 'layouts/navbar.html' %}

{% block content %}{% endblock %}


{% include 'layouts/footer.html' %}

news/templates/pages/about/about.html
{% extends 'master/master.html' %}
{% block content %}
<h1>About Page</h1>
{% endblock %}

news/templates/pages/blogs/blog.html
{% extends 'master/master.html' %}
{% block content %}
<div class="container">
    <div class="col-md-6 tn-left">
        <h3><a href="{% url 'blog_add' %}" ><button class="btn btn-success" style="margin-top:50px">Add New Blog</button></a></h3>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        {% endif %}
    </div>
</div>
    <!-- Top Blog Start-->
        <div class="top-news">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 tn-left">
                        <div class="row tn-slider">
                            {% for blogs in blogsData %}
                            <div class="col-md-6">
                                <div class="tn-img">
                                    {% if blogs.image %}
                                    <img src="{{blogs.image.url}}" height="300" alt="{{blogs.title}}"/>
                                    {% endif %}
                                    <div class="tn-title">
                                        <a href="{% url 'blog_details' blogs.slug %}">{{blogs.title}}</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-6 tn-right">
                        <div class="row tn-slider">
                            {% for blogs in blogsData %}
                            <div class="col-md-6">
                                <div class="tn-img">
                                    {% if blogs.image %}
                                    <img src="{{blogs.image.url}}" height="300" alt="{{blogs.title}}"/>
                                    {% endif %}
                                    <div class="tn-title">
                                        <a href="{% url 'blog_details' blogs.slug %}">{{blogs.title}}</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="top-news">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 tn-left">
                        <div class="row tn-slider">
                            {% for blogs in blogsData %}
                            <div class="col-md-6">
                                <div class="tn-img">
                                    {% if blogs.image %}
                                    <img src="{{blogs.image.url}}" height="300" alt="{{blogs.title}}"/>
                                    {% endif %}
                                    <div class="tn-title">
                                        <a href="{% url 'blog_details' blogs.slug %}">{{blogs.title}}</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-6 tn-right">
                        <div class="row tn-slider">
                            {% for blogs in blogsData %}
                            <div class="col-md-6">
                                <div class="tn-img">
                                    {% if blogs.image %}
                                    <img src="{{blogs.image.url}}" height="300" alt="{{blogs.title}}"/>
                                    {% endif %}
                                    <div class="tn-title">
                                        <a href="{% url 'blog_details' blogs.slug %}">{{blogs.title}}</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top News End-->
{% endblock %}

news/templates/pages/blogs/blog_add.html
{% extends 'master/master.html' %}
{% block content %}

<!--Add Blog Start-->
<div class="row">
    <div class="col-md-12">
        <h1 style="margin:30px">Add Your Blog</h1>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <form style="margin-left:50px" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group mb-3">
                <label for="title">Title:</label>
                <input type="text" id="title" name="title" required class="form-control" />
            </div>
            <div class="form-group mb-3">
                <label for="title">Author:</label>
                <input type="text" id="author" name="author" required class="form-control" />
            </div>
            <div class="form-group mb-3">
                <label for="intro">Intro:</label>
                <input type="text" id="intro" name="intro" required class="form-control" />
            </div>
            <div class="form-group mb-3">
                <label for="content">Content:</label>
                <input type="text" id="content" name="content" required class="form-control" />
            </div>
            <div class="form-group mb-3">
                <label for="image">Image:</label>
                <input type="file" name="image" class="btn btn-outline-dark" />
            </div>
            <div class="form-group mb-3">
            <button class="btn btn-outline-success"><i class="bi bi-plus-circle"></i>Post Blog</button>
            </div>
        </form>
    </div>
</div>
<!--Add Blog End-->

{% endblock %}

news/templates/pages/blogs/blog_details.html
{% extends 'master/master.html' %}
{% block content %}

        <!-- Breadcrumb Start -->
        <div class="breadcrumb-wrap">
            <div class="container">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                    <li class="breadcrumb-item active">{{blogsData.title}}</li>
                </ul>
            </div>
        </div>
        <!-- Breadcrumb End -->
        <div>
        <!-- Single News Start-->
        <div class="single-news">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="sn-container">
                            {% if blogsData.image %}
                            <div class="sn-img">
                                <img src="{{blogsData.image.url}}" width="100%" alt="{{blogsData.title}}"/>
                            </div>
                            {% endif %}
                            <div class="btn-default">
                                <div class="container">
                                    <a href="{%url 'blog_update' blogsData.slug %}" class="btn btn-outline-success" style="margin-top:30px">Update Blog
                                    </a>
                                    <a href="{%url 'blog_delete' blogsData.slug %}" onclick="return confirm('Are You Sure?')" class="btn btn-outline-danger" style="margin-top:30px">Delete Blog
                                    </a>
                                </div>
                            </div>
                            <div class="sn-content">
                                <h1 class="sn-title">{{blogsData.title}}</h1>
                                <p><b>By : {{blogsData.author}}</b></p>
                                <p><b>{{blogsData.date}}</b></p>
                                <p>
                                    {{blogsData.intro |safe}}
                                </p>
                                <p>
                                    {{blogsData.content |safe}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Single News End-->        

{% endblock %}

news/templates/pages/home/index.html
{% extends 'master/master.html' %}
{% block content %}

        <!-- Top News Start-->
        <div class="top-news">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 tn-left">
                        <div class="row tn-slider">
                            {% for news in newsData %}
                            <div class="col-md-6">
                                <div class="tn-img">
                                    {% if news.image %}
                                    <img src="{{news.image.url}}" height="300" alt="{{news.title}}"/>
                                    {% endif %}
                                    <div class="tn-title">
                                        <a href="{% url 'news_details' news.slug %}">{{news.title}}</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-6 tn-right">
                        <div class="row tn-slider">
                            {% for news in newsData %}
                            <div class="col-md-6">
                                <div class="tn-img">
                                    {% if news.image %}
                                    <img src="{{news.image.url}}" height="300" alt="{{news.title}}"/>
                                    {% endif %}
                                    <div class="tn-title">
                                        <a href="{% url 'news_details' news.slug %}">{{news.title}}</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Top News End-->

        <!-- Category News Start-->
        <div class="cat-news">
            <div class="container">
                <div class="row">
                    {% for category in CategoryData%}
                    <div class="col-md-6">
                        <h2>{{category.category_name}}</h2>
                        <div class="row cn-slider">
                            {% comment %} Related News {% endcomment %}
                            {% for news in category.news_set.all %}
                            <div class="col-md-6">
                                {% if news.image %}
                                <div class="cn-img">
                                    <img src="{{news.image.url}}" height="200" alt="{{news.title}}"/>
                                {% endif %}
                                    <div class="cn-title">
                                        <a href="{% url 'news_details' news.slug %}">{{news.title}}</a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Category News End-->

        <!-- Tab News Start-->
        <div class="tab-news">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <ul class="nav nav-pills nav-justified">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="pill" href="#most_viewed">Most Viewed News</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tn-news">
                                <div id="most_viewed">
                                    {% for news in most_viewed_news %}
                                        {% if news.image %}
                                            <div class="tn-img">
                                                <img src="{{news.image.url}}" alt="{{news.title}}"/>
                                            </div>
                                        {% endif %}
                                        <div class="tn-title">
                                            <a href="{% url 'news_details' news.slug %}">{{news.title}}</a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Tab News Start-->


{% endblock %}